### ISSUE TITLE
Разработать примерный дизайн сайта

### ISSUE THREAD

**Issue by AexsandR** [AexsandR/NGBox#3]
выполнить до 01.11.23

**Comment by Visherrrix** [comment]
Не по смарту чутка, моя твоя не разуметь
Что конкретно нужно успеть?
Имеешь в виду фон, кнопки или всё вместе? И мне нужно знание ваших пожеланий/мыслей касательно атмосферы игры, чтобы было от чего отталкиваться

**Comment by AexsandR** [comment]
нужно придумать дизайн кнопок, полей ввода, фон и подобрать шрифт. " И мне нужно знание ваших пожеланий/мыслей касательно атмосферы игры, чтобы было от чего отталкиваться"  на своё усмотрение. И еще у тебя дедлайн переносится на 03.11.23, я вспомнил, что ты орг. мероприятия.
